# file: tasks/dependencies.yml
---
- name: install debian dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - libtool
    - make
    # - libc6-dev
  when: ansible_os_family == "Debian"

- name: install redhat dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    # - gcc-c++
    # - libtool
    - make    
  when: ansible_os_family == "RedHat"

- name: install suse dependencies
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
  when: ansible_os_family == 'Suse'