# file: tasks/download.yml
---
- name: download | Check if local file is already configured.
  stat: "path={{ archive_path }}/{{ archive_file }}"
  connection: local
  register: archive_file_result
  tags:
    - download

- name: download | Create software directory.
  file: "path={{ archive_path }} state=directory"
  connection: local
  when: not archive_file_result.stat.exists
  tags:
    - download

- name: download | Download software file.
  get_url: "url={{ archive_url }}/{{ archive_file }} dest={{ archive_path }}"
  connection: local
  when: 
    - not archive_file_result.stat.exists
    - using_url
    - archive_url !=""
    - archive_file != ""
  tags:
    - download

- name: download | Download software file.
  get_url: "url={{ dlserver }}/{{ archive_file }} dest={{ archive_path }}"
  connection: local
  when: 
    - not archive_file_result.stat.exists
    - not using_url
    - archive_file != ""
  tags:
    - download