# file: tasks/install.yml
---
- name: install | Copy redis file to agent.
  unarchive:
    src: "{{ archive_path }}/{{ archive_file }}"
    # dest: "/usr/local/src"
    # creates: /usr/local/src/redis-{{ redis_version }}/Makefile
    dest: "/tmp/"
    creates: "/tmp/redis-{{ redis_version }}/Makefile"

- name: install | Confirm the existence of the installation directory.
  file: path="{{ app_base_path }}/redis-{{ redis_version }}" state=directory

- name: install | Compile redis.
  shell: "make"
  args:
    chdir: "/tmp/redis-{{ redis_version }}"
    creates: "{{ app_base_path }}/redis-{{ redis_version }}/bin"

- name: install | Build redis.
  shell: "make PREFIX={{ app_base_path }}/redis-{{ redis_version }} install"
  args:
    chdir: "/tmp/redis-{{ redis_version }}"
    creates: "{{ app_base_path }}/redis-{{ redis_version }}/bin"

- name: install | Check if redis remote soft link is already configured.
  stat: path="{{ app_base_path }}/redis"
  register: redis_soft_link_result

- name: install | Create redis dir soft link.
  file: "src={{ app_base_path }}/redis-{{ redis_version }} dest={{ app_base_path }}/redis state=link"
  when: not redis_soft_link_result.stat.exists

- name: install | Copy redis-trib.rb to bin path.
  copy: "src=/tmp/redis-{{ redis_version }}/src/redis-trib.rb dest={{ app_base_path }}/redis-{{ redis_version }}/bin mode=755 remote_src=true"
  when: not redis_soft_link_result.stat.exists

- name: install | Config environment variable.
  lineinfile: dest=/etc/profile line='export PATH={{ app_base_path }}/redis/bin/:$PATH'
  run_once: yes